package createentity.util;

public class DocumentLogic {
	public static void main(String[] args) {
		String o = "podcast_show";
		String e = "private Long id;\r\n"
				+ "\r\n"
				+ "@Column(name = \"vendor_id\")\r\n"
				+ "private Long vendorId;\r\n"
				+ "\r\n"
				+ "@Column(name = \"vendor_name\")\r\n"
				+ "private String vendorName;\r\n"
				+ "\r\n"
				+ "private String title;\r\n"
				+ "\r\n"
				+ "@Column(name = \"publication_date\")\r\n"
				+ "private Date publicationDate;\r\n"
				+ "\r\n"
				+ "@Column(name = \"last_build_date\")\r\n"
				+ "private Date lastBuildDate;\r\n"
				+ "\r\n"
				+ "private String generator;\r\n"
				+ "\r\n"
				+ "private String link;\r\n"
				+ "\r\n"
				+ "private String language;\r\n"
				+ "\r\n"
				+ "private String copyright;\r\n"
				+ "\r\n"
				+ "private String docs;\r\n"
				+ "\r\n"
				+ "@Column(name = \"managing_editor\")\r\n"
				+ "private String managingEditor;\r\n"
				+ "\r\n"
				+ "private String summary;\r\n"
				+ "\r\n"
				+ "@Column(name = \"image_url\")\r\n"
				+ "private String imageUrl;\r\n"
				+ "\r\n"
				+ "private String author;\r\n"
				+ "\r\n"
				+ "private String keywords;\r\n"
				+ "\r\n"
				+ "private String categories;\r\n"
				+ "\r\n"
				+ "private Integer status;\r\n"
				+ "\r\n"
				+ "@Column(name = \"created_on\")\r\n"
				+ "private Date createdOn;\r\n"
				+ "\r\n"
				+ "@Column(name = \"modified_on\")\r\n"
				+ "private Date modifiedOn;\r\n"
				+ "\r\n"
				+ "private Integer pop24hrs;\r\n"
				+ "\r\n"
				+ "private Integer pop7days;\r\n"
				+ "\r\n"
				+ "private Integer pop30days;\r\n"
				+ "\r\n"
				+ "private Integer popall;\r\n"
				+ "\r\n"
				+ "@Column(name = \"podcast_type\")\r\n"
				+ "private Integer podcastType;\r\n"
				+ "\r\n"
				+ "@Column(name = \"display_rule_id\")\r\n"
				+ "private Long displayRuleId;\r\n"
				+ "\r\n"
				+ "private String artwork;\r\n"
				+ "\r\n"
				+ "private String icon;\r\n"
				+ "\r\n"
				+ "@Column(name = \"negative_list_web\")\r\n"
				+ "private String negativeListWeb;\r\n"
				+ "\r\n"
				+ "@Column(name = \"negative_list_mobile\")\r\n"
				+ "private String negativeListMobile;\r\n"
				+ "\r\n"
				+ "@Column(name = \"saarc_privilege_id\")\r\n"
				+ "private Long saarcPrivilegeId;\r\n"
				+ "\r\n"
				+ "@Column(name = \"season_order\")\r\n"
				+ "private Integer seasonOrder;\r\n"
				+ "\r\n"
				+ "@Column(name = \"is_show_ep_img\")\r\n"
				+ "private Integer isShowEpImg;\r\n"
				+ "\r\n"
				+ "@Column(name = \"total_favourite_count\")\r\n"
				+ "private Integer totalFavouriteCount;\r\n"
				+ "\r\n"
				+ "@Column(name = \"artists_list\")\r\n"
				+ "private String artistsList;\r\n"
				+ "\r\n"
				+ "@Column(name = \"is_sponsored\")\r\n"
				+ "private Integer isSponsored;\r\n"
				+ "\r\n"
				+ "@Column(name = \"modified_on_solr\")\r\n"
				+ "private Date modifiedOnSolr;\r\n"
				+ "\r\n"
				+ "@Column(name = \"season_seokey\")\r\n"
				+ "private String seasonSeokey;\r\n"
				+ "\r\n"
				+ "@Column(name = \"ep_order\")\r\n"
				+ "private Integer epOrder;\r\n"
				+ "\r\n"
				+ "@Column(name = \"total_episodes\")\r\n"
				+ "private Integer totalEpisodes;\r\n"
				+ "\r\n"
				+ "@Column(name = \"v_atw\")\r\n"
				+ "private String vAtw;\r\n"
				+ "\r\n"
				+ "@Column(name = \"is_migrated\")\r\n"
				+ "private Integer isMigrated;\r\n"
				+ "\r\n"
				+ "@Column(name = \"is_manually_atw\")\r\n"
				+ "private Integer isManuallyAtw;\r\n"
				+ "\r\n"
				+ "@Column(name = \"classification_id\")\r\n"
				+ "private Long classificationId;\r\n"
				+ "\r\n"
				+ "@Column(name = \"created_by\")\r\n"
				+ "private Integer createdBy;\r\n"
				+ "\r\n"
				+ "@Column(name = \"modified_by\")\r\n"
				+ "private Integer modifiedBy;\r\n"
				+ "\r\n"
				+ "@Column(name = \"secondary_language\")\r\n"
				+ "private String secondaryLanguage;\r\n"
				+ "\r\n"
				+ "@Column(name = \"app_summary\")\r\n"
				+ "private String appSummary;\r\n"
				+ "\r\n"
				+ "@Column(name = \"parental_warning\")\r\n"
				+ "private Integer parentalWarning;\r\n"
				+ "\r\n"
				+ "@Column(name = \"contracting_party_name\")\r\n"
				+ "private String contractingPartyName;\r\n"
				+ "\r\n"
				+ "@Column(name = \"is_preview\")\r\n"
				+ "private Integer isPreview;\r\n"
				+ "\r\n"
				+ "@Column(name = \"all_categories\")\r\n"
				+ "private String allCategories;\r\n"
				+ "\r\n"
				+ "@Column(name = \"manual_categories\")\r\n"
				+ "private String manualCategories;\r\n"
				+ "\r\n"
				+ "@Column(name = \"feed_resource\")\r\n"
				+ "private Integer feedResource;\r\n"
				+ "\r\n"
				+ "@Column(name = \"category_upadated_on\")\r\n"
				+ "private Date categoryUpadatedOn;\r\n"
				+ "\r\n"
				+ "@Column(name = \"gaana_user_id\")\r\n"
				+ "private Long gaanaUserId;\r\n"
				+ "\r\n"
				+ "@Column(name = \"meta_title\")\r\n"
				+ "private String metaTitle;\r\n"
				+ "\r\n"
				+ "@Column(name = \"meta_description\")\r\n"
				+ "private String metaDescription;\r\n"
				+ "\r\n"
				+ "@Column(name = \"meta_keywords\")\r\n"
				+ "private String metaKeywords;\r\n"
				+ "\r\n"
				+ "@Column(name = \"meta_h1_tag\")\r\n"
				+ "private String metaH1Tag;\r\n"
				+ "\r\n"
				+ "private String artists;\r\n"
				+ "\r\n"
				+ "@Column(name = \"editor_review_check\")\r\n"
				+ "private Integer editorReviewCheck;\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "";
		String[] es = e.split("\n");
		for (String s : es) {
			s = s.trim();
//			System.out.println(s);
			if (s.trim().equals("") || s.trim().startsWith("@") || s.trim().startsWith("\r")) {
				continue;
			}
			String name = s.substring(s.lastIndexOf(" ") + 1, s.lastIndexOf(";"));
			String regex = "([a-z])([A-Z]+)";
			String replacement = "$1_$2";
			String name_ = name.replaceAll(regex, replacement).toLowerCase();
			String r = "@ApiModelProperty(notes = \"" + name_ + " - " + name + " in " + o + "\")\n" + s;
			System.out.println(r);
		}
	}
}
