package createentity.util;

import java.util.Objects;

public class PopulateLogic {
	public static void main(String[] args) {
		String o = "album";
		String e = "@ApiModelProperty(notes = \"cached - cached in album\")\r\n"
				+ "	private Short cached;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"title - title in album\")\r\n"
				+ "	private String title;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"artists - artists in album\")\r\n"
				+ "	private String artists;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"composer - composer in album\")\r\n"
				+ "	private String composer;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"moods - moods in album\")\r\n"
				+ "	private String moods;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"genere - genere in album\")\r\n"
				+ "	private String genere;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"subgenere - subgenere in album\")\r\n"
				+ "	private String subgenere;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"description - description in album\")\r\n"
				+ "	private String description;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"release_year - releaseYear in album\")\r\n"
				+ "	private Integer releaseYear;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"release_date - releaseDate in album\")\r\n"
				+ "	private Date releaseDate;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"movie_release_date - movieReleaseDate in album\")\r\n"
				+ "	private Date movieReleaseDate;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"album_cost - albumCost in album\")\r\n"
				+ "	private Double albumCost;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"language - language in album\")\r\n"
				+ "	private String language;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"vendor_id - vendorId in album\")\r\n"
				+ "	private Integer vendorId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"ref_album_code - refAlbumCode in album\")\r\n"
				+ "	private String refAlbumCode;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"mime - mime in album\")\r\n"
				+ "	private String mime;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"vendor_name - vendorName in album\")\r\n"
				+ "	private String vendorName;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"original_artwork_file_path - originalArtworkFilePath in album\")\r\n"
				+ "	private String originalArtworkFilePath;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"upc - upc in album\")\r\n"
				+ "	private String upc;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"enable_paid_trail - enablePaidTrail in album\")\r\n"
				+ "	private Boolean enablePaidTrail;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"search_keyword - searchKeyword in album\")\r\n"
				+ "	private String searchKeyword;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"type - type in album\")\r\n"
				+ "	private Boolean type;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"negative_list_web - negativeListWeb in album\")\r\n"
				+ "	private String negativeListWeb;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"negative_list_mobile - negativeListMobile in album\")\r\n"
				+ "	private String negativeListMobile;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"only_for_paid_user - onlyForPaidUser in album\")\r\n"
				+ "	private Boolean onlyForPaidUser;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"is_movie - isMovie in album\")\r\n"
				+ "	private Short isMovie;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"album_display_geo - albumDisplayGeo in album\")\r\n"
				+ "	private Set<String> albumDisplayGeo;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"mobile_saarc - mobileSaarc in album\")\r\n"
				+ "	private Short mobileSaarc;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"web_saarc - webSaarc in album\")\r\n"
				+ "	private Short webSaarc;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"primary_artist - primaryArtist in album\")\r\n"
				+ "	private String primaryArtist;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"primary_artist_type - primaryArtistType in album\")\r\n"
				+ "	private String primaryArtistType;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"ingestion_from_script - ingestionFromScript in album\")\r\n"
				+ "	private boolean ingestionFromScript;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"ablum_source - ablumSource in album\")\r\n"
				+ "	private Integer ablumSource;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"solr_not_searchable - solrNotSearchable in album\")\r\n"
				+ "	private boolean solrNotSearchable;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"created_by - createdBy in album\")\r\n"
				+ "	private Long createdBy;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"aid - aid in album\")\r\n"
				+ "	private Long aid;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"ibbd - ibbd in album\")\r\n"
				+ "	private boolean ibbd;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"sponsored - sponsored in album\")\r\n"
				+ "	private boolean sponsored;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"language_ids - languageIds in album\")\r\n"
				+ "	private List<Long> languageIds;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"manually_boost - manuallyBoost in album\")\r\n"
				+ "	private boolean manuallyBoost;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"album_id - albumId in album\")\r\n"
				+ "	private Long albumId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"cast - cast in album\")\r\n"
				+ "	private String cast;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"sapid - sapid in album\")\r\n"
				+ "	private Integer sapid;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"sub_vendor - subVendor in album\")\r\n"
				+ "	private String subVendor;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"seokey - seokey in album\")\r\n"
				+ "	private String seokey;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"alias - alias in album\")\r\n"
				+ "	private String alias;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"artists_list - artistsList in album\")\r\n"
				+ "	private String artistsList;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"composer_list - composerList in album\")\r\n"
				+ "	private String composerList;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"primary_composer - primaryComposer in album\")\r\n"
				+ "	private String primaryComposer;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"genere_list - genereList in album\")\r\n"
				+ "	private String genereList;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"cast_list - castList in album\")\r\n"
				+ "	private String castList;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"artwork - artwork in album\")\r\n"
				+ "	private String artwork;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"tracks_ids - tracksIds in album\")\r\n"
				+ "	private String tracksIds;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"track_count - trackCount in album\")\r\n"
				+ "	private Integer trackCount;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"duration - duration in album\")\r\n"
				+ "	private Integer duration;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"format - format in album\")\r\n"
				+ "	private String format;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"bit_rate - bitRate in album\")\r\n"
				+ "	private Integer bitRate;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"file_size - fileSize in album\")\r\n"
				+ "	private String fileSize;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"created_on - createdOn in album\")\r\n"
				+ "	private Date createdOn;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"modified_on - modifiedOn in album\")\r\n"
				+ "	private Date modifiedOn;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"modified_by - modifiedBy in album\")\r\n"
				+ "	private Integer modifiedBy;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"status - status in album\")\r\n"
				+ "	private Integer status;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"activated_on - activatedOn in album\")\r\n"
				+ "	private Date activatedOn;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"pop24hrs - pop24hrs in album\")\r\n"
				+ "	private Long pop24hrs;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"pop7days - pop7days in album\")\r\n"
				+ "	private Long pop7days;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"pop30days - pop30days in album\")\r\n"
				+ "	private Long pop30days;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"popall - popall in album\")\r\n"
				+ "	private Long popall;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"display_global - displayGlobal in album\")\r\n"
				+ "	private Boolean displayGlobal;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"expiry_date - expiryDate in album\")\r\n"
				+ "	private Date expiryDate;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"qc - qc in album\")\r\n"
				+ "	private String qc;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"content_source - contentSource in album\")\r\n"
				+ "	private Integer contentSource;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"content_provider_id - contentProviderId in album\")\r\n"
				+ "	private Integer contentProviderId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"status_change_date - statusChangeDate in album\")\r\n"
				+ "	private Date statusChangeDate;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"merge_album_id - mergeAlbumId in album\")\r\n"
				+ "	private Integer mergeAlbumId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"display_rule_id - displayRuleId in album\")\r\n"
				+ "	private Integer displayRuleId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"total_favourite_count - totalFavouriteCount in album\")\r\n"
				+ "	private Integer totalFavouriteCount;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"adcode_topslug - adcodeTopslug in album\")\r\n"
				+ "	private String adcodeTopslug;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"adcode_bottomslug - adcodeBottomslug in album\")\r\n"
				+ "	private String adcodeBottomslug;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"adcode_interstitial - adcodeInterstitial in album\")\r\n"
				+ "	private String adcodeInterstitial;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"adcode_playerloader - adcodePlayerloader in album\")\r\n"
				+ "	private String adcodePlayerloader;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"saarc_privilege_id - saarcPrivilegeId in album\")\r\n"
				+ "	private Short saarcPrivilegeId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"modifed_on_solr - modifedOnSolr in album\")\r\n"
				+ "	private Date modifedOnSolr;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"sync_on_vsnl - syncOnVsnl in album\")\r\n"
				+ "	private Boolean syncOnVsnl;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"medianet_id - medianetId in album\")\r\n"
				+ "	private Integer medianetId;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"is_enable_paid_trail - isEnablePaidTrail in album\")\r\n"
				+ "	private Boolean isEnablePaidTrail;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"is_webp - isWebp in album\")\r\n"
				+ "	private Boolean isWebp;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"artwork_version - artworkVersion in album\")\r\n"
				+ "	private Short artworkVersion;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"meta_title - metaTitle in album\")\r\n"
				+ "	private String metaTitle;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"meta_description - metaDescription in album\")\r\n"
				+ "	private String metaDescription;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"meta_keywords - metaKeywords in album\")\r\n"
				+ "	private String metaKeywords;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"meta_h1tag - metaH1Tag in album\")\r\n"
				+ "	private String metaH1Tag;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"parental_warning - parentalWarning in album\")\r\n"
				+ "	private Short parentalWarning;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"artwork_v1 - artworkV1 in album\")\r\n"
				+ "	private String artworkV1;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"is_downloadable - isDownloadable in album\")\r\n"
				+ "	private Short isDownloadable;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"free_downloadable - freeDownloadable in album\")\r\n"
				+ "	private Short freeDownloadable;\r\n"
				+ "\r\n"
				+ "	@ApiModelProperty(notes = \"listing_active - listingActive in album\")\r\n"
				+ "	private Short listingActive;\r\n"
				+ "";
		String[] es = e.split("\n");
		for (String s : es) {
			if(!s.contains(";")) {
				continue;
			}
			String name = s.substring(s.lastIndexOf(" ")+1, s.lastIndexOf(";"));
//			System.out.println(name);
			name = name.substring(0,1).toUpperCase()+name.substring(1);
			String r = "if(!Objects.isNull(request.get"+name+"())) {\r\n"
					+ "			"+o+".set"+name+"(request.get"+name+"());\r\n"
					+ "		}";
			System.out.println(r);
		}
	}
}
