package createentity.util;

public class ServiceMapperLogic {
	public static void main(String[] args) {
		String n = "podcast";
		String o = "PodcastResponse";
		String e = "@ApiModelProperty(notes = \"id - id in podcast_show\")\r\n"
				+ "	private Long id;\r\n"
				+ "	@ApiModelProperty(notes = \"vendor_id - vendorId in podcast_show\")\r\n"
				+ "	private Long vendorId;\r\n"
				+ "	@ApiModelProperty(notes = \"vendor_name - vendorName in podcast_show\")\r\n"
				+ "	private String vendorName;\r\n"
				+ "	@ApiModelProperty(notes = \"title - title in podcast_show\")\r\n"
				+ "	private String title;\r\n"
				+ "	@ApiModelProperty(notes = \"publication_date - publicationDate in podcast_show\")\r\n"
				+ "	private Date publicationDate;\r\n"
				+ "	@ApiModelProperty(notes = \"last_build_date - lastBuildDate in podcast_show\")\r\n"
				+ "	private Date lastBuildDate;\r\n"
				+ "	@ApiModelProperty(notes = \"generator - generator in podcast_show\")\r\n"
				+ "	private String generator;\r\n"
				+ "	@ApiModelProperty(notes = \"link - link in podcast_show\")\r\n"
				+ "	private String link;\r\n"
				+ "	@ApiModelProperty(notes = \"language - language in podcast_show\")\r\n"
				+ "	private String language;\r\n"
				+ "	@ApiModelProperty(notes = \"copyright - copyright in podcast_show\")\r\n"
				+ "	private String copyright;\r\n"
				+ "	@ApiModelProperty(notes = \"docs - docs in podcast_show\")\r\n"
				+ "	private String docs;\r\n"
				+ "	@ApiModelProperty(notes = \"managing_editor - managingEditor in podcast_show\")\r\n"
				+ "	private String managingEditor;\r\n"
				+ "	@ApiModelProperty(notes = \"summary - summary in podcast_show\")\r\n"
				+ "	private String summary;\r\n"
				+ "	@ApiModelProperty(notes = \"image_url - imageUrl in podcast_show\")\r\n"
				+ "	private String imageUrl;\r\n"
				+ "	@ApiModelProperty(notes = \"author - author in podcast_show\")\r\n"
				+ "	private String author;\r\n"
				+ "	@ApiModelProperty(notes = \"keywords - keywords in podcast_show\")\r\n"
				+ "	private String keywords;\r\n"
				+ "	@ApiModelProperty(notes = \"categories - categories in podcast_show\")\r\n"
				+ "	private String categories;\r\n"
				+ "	@ApiModelProperty(notes = \"status - status in podcast_show\")\r\n"
				+ "	private Integer status;\r\n"
				+ "	@ApiModelProperty(notes = \"created_on - createdOn in podcast_show\")\r\n"
				+ "	private Date createdOn;\r\n"
				+ "	@ApiModelProperty(notes = \"modified_on - modifiedOn in podcast_show\")\r\n"
				+ "	private Date modifiedOn;\r\n"
				+ "	@ApiModelProperty(notes = \"pop24hrs - pop24hrs in podcast_show\")\r\n"
				+ "	private Integer pop24hrs;\r\n"
				+ "	@ApiModelProperty(notes = \"pop7days - pop7days in podcast_show\")\r\n"
				+ "	private Integer pop7days;\r\n"
				+ "	@ApiModelProperty(notes = \"pop30days - pop30days in podcast_show\")\r\n"
				+ "	private Integer pop30days;\r\n"
				+ "	@ApiModelProperty(notes = \"popall - popall in podcast_show\")\r\n"
				+ "	private Integer popall;\r\n"
				+ "	@ApiModelProperty(notes = \"podcast_type - podcastType in podcast_show\")\r\n"
				+ "	private Integer podcastType;\r\n"
				+ "	@ApiModelProperty(notes = \"display_rule_id - displayRuleId in podcast_show\")\r\n"
				+ "	private Long displayRuleId;\r\n"
				+ "	@ApiModelProperty(notes = \"artwork - artwork in podcast_show\")\r\n"
				+ "	private String artwork;\r\n"
				+ "	@ApiModelProperty(notes = \"icon - icon in podcast_show\")\r\n"
				+ "	private String icon;\r\n"
				+ "	@ApiModelProperty(notes = \"negative_list_web - negativeListWeb in podcast_show\")\r\n"
				+ "	private String negativeListWeb;\r\n"
				+ "	@ApiModelProperty(notes = \"negative_list_mobile - negativeListMobile in podcast_show\")\r\n"
				+ "	private String negativeListMobile;\r\n"
				+ "	@ApiModelProperty(notes = \"saarc_privilege_id - saarcPrivilegeId in podcast_show\")\r\n"
				+ "	private Long saarcPrivilegeId;\r\n"
				+ "	@ApiModelProperty(notes = \"season_order - seasonOrder in podcast_show\")\r\n"
				+ "	private Integer seasonOrder;\r\n"
				+ "	@ApiModelProperty(notes = \"is_show_ep_img - isShowEpImg in podcast_show\")\r\n"
				+ "	private Integer isShowEpImg;\r\n"
				+ "	@ApiModelProperty(notes = \"total_favourite_count - totalFavouriteCount in podcast_show\")\r\n"
				+ "	private Integer totalFavouriteCount;\r\n"
				+ "	@ApiModelProperty(notes = \"artists_list - artistsList in podcast_show\")\r\n"
				+ "	private String artistsList;\r\n"
				+ "	@ApiModelProperty(notes = \"is_sponsored - isSponsored in podcast_show\")\r\n"
				+ "	private Integer isSponsored;\r\n"
				+ "	@ApiModelProperty(notes = \"modified_on_solr - modifiedOnSolr in podcast_show\")\r\n"
				+ "	private Date modifiedOnSolr;\r\n"
				+ "	@ApiModelProperty(notes = \"season_seokey - seasonSeokey in podcast_show\")\r\n"
				+ "	private String seasonSeokey;\r\n"
				+ "	@ApiModelProperty(notes = \"ep_order - epOrder in podcast_show\")\r\n"
				+ "	private Integer epOrder;\r\n"
				+ "	@ApiModelProperty(notes = \"total_episodes - totalEpisodes in podcast_show\")\r\n"
				+ "	private Integer totalEpisodes;\r\n"
				+ "	@ApiModelProperty(notes = \"v_atw - vAtw in podcast_show\")\r\n"
				+ "	private String vAtw;\r\n"
				+ "	@ApiModelProperty(notes = \"is_migrated - isMigrated in podcast_show\")\r\n"
				+ "	private Integer isMigrated;\r\n"
				+ "	@ApiModelProperty(notes = \"is_manually_atw - isManuallyAtw in podcast_show\")\r\n"
				+ "	private Integer isManuallyAtw;\r\n"
				+ "	@ApiModelProperty(notes = \"classification_id - classificationId in podcast_show\")\r\n"
				+ "	private Long classificationId;\r\n"
				+ "	@ApiModelProperty(notes = \"created_by - createdBy in podcast_show\")\r\n"
				+ "	private Integer createdBy;\r\n"
				+ "	@ApiModelProperty(notes = \"modified_by - modifiedBy in podcast_show\")\r\n"
				+ "	private Integer modifiedBy;\r\n"
				+ "	@ApiModelProperty(notes = \"secondary_language - secondaryLanguage in podcast_show\")\r\n"
				+ "	private String secondaryLanguage;\r\n"
				+ "	@ApiModelProperty(notes = \"app_summary - appSummary in podcast_show\")\r\n"
				+ "	private String appSummary;\r\n"
				+ "	@ApiModelProperty(notes = \"parental_warning - parentalWarning in podcast_show\")\r\n"
				+ "	private Integer parentalWarning;\r\n"
				+ "	@ApiModelProperty(notes = \"contracting_party_name - contractingPartyName in podcast_show\")\r\n"
				+ "	private String contractingPartyName;\r\n"
				+ "	@ApiModelProperty(notes = \"is_preview - isPreview in podcast_show\")\r\n"
				+ "	private Integer isPreview;\r\n"
				+ "	@ApiModelProperty(notes = \"all_categories - allCategories in podcast_show\")\r\n"
				+ "	private String allCategories;\r\n"
				+ "	@ApiModelProperty(notes = \"manual_categories - manualCategories in podcast_show\")\r\n"
				+ "	private String manualCategories;\r\n"
				+ "	@ApiModelProperty(notes = \"feed_resource - feedResource in podcast_show\")\r\n"
				+ "	private Integer feedResource;\r\n"
				+ "	@ApiModelProperty(notes = \"category_upadated_on - categoryUpadatedOn in podcast_show\")\r\n"
				+ "	private Date categoryUpadatedOn;\r\n"
				+ "	@ApiModelProperty(notes = \"gaana_user_id - gaanaUserId in podcast_show\")\r\n"
				+ "	private Long gaanaUserId;\r\n"
				+ "	@ApiModelProperty(notes = \"meta_title - metaTitle in podcast_show\")\r\n"
				+ "	private String metaTitle;\r\n"
				+ "	@ApiModelProperty(notes = \"meta_description - metaDescription in podcast_show\")\r\n"
				+ "	private String metaDescription;\r\n"
				+ "	@ApiModelProperty(notes = \"meta_keywords - metaKeywords in podcast_show\")\r\n"
				+ "	private String metaKeywords;\r\n"
				+ "	@ApiModelProperty(notes = \"meta_h1tag - metaH1Tag in podcast_show\")\r\n"
				+ "	private String metaH1Tag;\r\n"
				+ "	@ApiModelProperty(notes = \"artists - artists in podcast_show\")\r\n"
				+ "	private String artists;\r\n"
				+ "	@ApiModelProperty(notes = \"editor_review_check - editorReviewCheck in podcast_show\")\r\n"
				+ "	private Integer editorReviewCheck;";
		String[] es = e.split("\n");
		String f = o + ".builder()";
		System.out.println(f);
		for (String s : es) {
			if(s.trim().equals("") || s.trim().startsWith("@") || s.trim().startsWith("\r")) {
				continue;
			}
			String name = s.substring(s.lastIndexOf(" ") + 1, s.lastIndexOf(";"));
			String name1Cap = name.substring(0, 1).toUpperCase() + name.substring(1);
			String r = "." + name + "("+n+".get" + name1Cap + "())";
			System.out.println(r);
		}
	}
}
